services:
  nele-challenge:
    image: itzg/minecraft-server
    container_name: nele-challenge
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.21.5
      INIT_MEMORY: 4G
      MAX_MEMORY: 12G
      TZ: Europe/Berlin
      MOTD: "§x§a§6§d§4§5§3>§x§a§1§d§1§5§4>§x§9§c§c§e§5§4 §x§9§7§c§b§5§5N§x§9§3§c§7§5§6E§x§8§e§c§4§5§7L§x§8§9§c§1§5§7E§x§8§4§b§e§5§8'§x§7§f§b§b§5§9S§x§7§a§b§8§5§a §x§7§5§b§5§5§aC§x§7§1§b§1§5§bH§x§6§c§a§e§5§cA§x§6§7§a§b§5§cL§x§6§2§a§8§5§dL§x§5§d§a§5§5§eE§x§5§8§a§2§5§fN§x§5§3§9§f§5§fG§x§4§e§9§c§6§0E§x§4§a§9§8§6§1 §x§4§5§9§5§6§1S§x§4§0§9§2§6§2E§x§3§b§8§f§6§3R§x§3§6§8§c§6§4V§x§3§1§8§9§6§4E§x§2§c§8§6§6§5R§x§2§8§8§2§6§6 §x§2§3§7§f§6§7<§x§1§e§7§c§6§7<"
      OPS: ${OPS}
      WHITELIST: ${WHITELIST}
      USE_MEOWICE_FLAGS: true
      ALLOW_NETHER: true
      ALLOW_FLIGHT: true
      MAX_PLAYERS: 787
      VIEW_DISTANCE: 10
      SIMULATION_DISTANCE: 6
      ONLINE_MODE: true
      SPAW_PROTECTION: 0
      ICON: /icon.png
      OVERRIDE_ICON: true
      MODRINTH_PROJECTS: "@/extras/modrinth.txt"
      RESOURCE_PACK: https://nextcloud.goett.top/s/pwYrHzFM8N35JFZ/download/NELE-SERVER.zip
      RESOURCE_PACK_SHA1: 25eb16dc6a83c6d826fd8b54cc0bd654ee1142dc
      RCON_CMDS_STARTUP: |-
        chunky shape circle
        chunky radius 2400
        chunky start
        chunky confirm
        chunky world world_nether
        chunky shape circle
        chunky radius 1000
        chunky start
        chunky world world_the_end
        chunky shape circle
        chunky radius 300
        chunky start
    restart: unless-stopped
    volumes:
      - ./nele-challenge/data:/data
      - ./icon.png:/icon.png
      - ./modrinth.txt:/extras/modrinth.txt:ro


  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: host
    restart: always
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=${DOMAINS}
      - PROXIED=false